### ISSUE TITLE
Non public constructors returns null and does not specify the cause

### ISSUE THREAD

**Issue by watarhu** [bytemechanics/service-repository#23]
If we try to use a service with one of it's non-public constructors the result is null and does not tell the underlaying cause for this error:

Example:
```
(...)
public class PersistenceUnitFactoryImpl implements PersistenceUnitFactory,Closeable{

	private final String persistenceUnit;
	private final EntityManagerFactory factory;	

	PersistenceUnitFactoryImpl(final String _persistenceUnit){
		try{
			this.persistenceUnit=_persistenceUnit;
			this.factory=createEntityManagerFactory(Collections.emptyMap());
		}catch(Throwable e){
			System.err.println("Error initiallizing persistenceUnit: "+e.getMessage());
			e.printStackTrace();
			throw e;
		}
	}
(...)
```

Throws:
> Caused by: org.bytemechanics.service.repository.exceptions.ServiceInitializationException: Service PERSISTENCEUNIT can not be initialized properly: Unable to instantiate service with class class com.allianz.ebcm.migration.tool.persistence.impl.PersistenceUnitFactoryImpl using constructor([ebcm-migration-tool])
> 	at org.bytemechanics.service.repository.ServiceSupplier.lambda$null$4(ServiceSupplier.java:217) ~[migration-tool-content-builder.jar:?]
> 	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_73]
> 	at org.bytemechanics.service.repository.ServiceSupplier.lambda$generateSupplier$5(ServiceSupplier.java:216) ~[migration-tool-content-builder.jar:?]
> 	at org.bytemechanics.service.repository.ServiceSupplier.get(ServiceSupplier.java:149) ~[migration-tool-content-builder.jar:?]
> 	at org.bytemechanics.service.repository.ServiceRepository.get(ServiceRepository.java:98) ~[migration-tool-content-builder.jar:?]
> 	at org.bytemechanics.service.repository.ServiceRepository.get(ServiceRepository.java:110) ~[migration-tool-content-builder.jar:?]
> 	at com.allianz.ebcm.migration.tool.persistence.JPAPersistenceDao.lambda$createEntityManager$1(JPAPersistenceDao.java:15) ~[migration-tool-content-builder.jar:?]
> 	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_73]
> 	at com.allianz.ebcm.migration.tool.persistence.JPAPersistenceDao.createEntityManager(JPAPersistenceDao.java:15) ~[migration-tool-content-builder.jar:?]
> 	at com.allianz.ebcm.migration.tool.business.services.impl.ContextServiceImpl.registerProcess(ContextServiceImpl.java:44) ~[migration-tool-content-builder.jar:?]
> 	at com.allianz.ebcm.migration.tool.business.services.impl.ContextServiceImpl.<init>(ContextServiceImpl.java:37) ~[migration-tool-content-builder.jar:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
> 	at org.bytemechanics.service.repository.internal.commons.reflection.ObjectFactory.lambda$null$5(ObjectFactory.java:153) ~[migration-tool-content-builder.jar:?]

This could not look like so important, but it's necessary in order to find easily the initialization error cause.

**Comment by watarhu** [comment]
Also happens if constructor is private or protected
